server {
    listen 80;
    # آدرس دامنه شما
    server_name panel.mediasanat.ir www.panel.mediasanat.ir;
    
    # اجازه آپلود عکس تا 50 مگابایت (برای محصولات ووکامرس)
    client_max_body_size 50M;

    location / {
        # هدایت ترافیک به سمت کانتینر جنگو
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # مسیردهی فایل‌های گرافیکی
    location /static/ {
        alias /app/staticfiles/;
    }

    # مسیردهی عکس‌های آپلودی
    location /media/ {
        alias /app/media/;
    }
}