# Generated by Django 6.0.5 on 2026-05-10 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='کد ویژگی (انگلیسی)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('max_products_per_month', models.IntegerField(default=10, verbose_name='حداکثر محصول در ماه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('features', models.ManyToManyField(blank=True, to='core.feature', verbose_name='ویژگی\u200cهای فعال')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('woo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس سایت ووکامرس')),
                ('woo_consumer_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید مشتری ووکامرس (Consumer Key)')),
                ('woo_consumer_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز مشتری ووکامرس (Consumer Secret)')),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید API هوش مصنوعی')),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن ربات پیام\u200cرسان')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت دسترسی فروشگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan', verbose_name='پلن اشتراک')),
            ],
            options={
                'verbose_name': 'فروشگاه (مستاجر)',
                'verbose_name_plural': 'فروشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('woo_product_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی محصول در ووکامرس')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق')], default='success', max_length=20, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا (در صورت وجود)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد کننده')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_logs', to='core.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'لاگ محصول',
                'verbose_name_plural': 'لاگ محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر فروشگاه'), ('operator', 'اپراتور')], default='operator', max_length=50, verbose_name='نقش کاربری')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.store', verbose_name='فروشگاه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
