# Generated by Django 6.0.5 on 2026-05-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_store_wp_app_password_store_wp_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه (مثلا: قطعات یخچال)')),
                ('url', models.URLField(max_length=500, verbose_name='لینک کامل (همراه با https)')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_links', to='core.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'لینک داخلی',
                'verbose_name_plural': 'لینک\u200cهای داخلی',
            },
        ),
    ]
