# Generated by Django 6.0.5 on 2026-05-13 05:57

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='bot_token',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن ربات پیام\u200cرسان')),
        ),
        migrations.AlterField(
            model_name='store',
            name='openai_api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید API هوش مصنوعی')),
        ),
        migrations.AlterField(
            model_name='store',
            name='woo_consumer_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز مشتری ووکامرس (Consumer Secret)')),
        ),
        migrations.AlterField(
            model_name='store',
            name='wp_app_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز عبور برنامه (Application Password)')),
        ),
    ]
