# Generated by Django 6.0.5 on 2026-05-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_store_bot_token_alter_store_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='action_type',
            field=models.CharField(choices=[('add', 'افزودن محصول'), ('update', 'ویرایش محصول')], default='add', max_length=10, verbose_name='نوع عملیات'),
        ),
        migrations.AddField(
            model_name='productlog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات تغییرات قیمت و موجودی'),
        ),
    ]
