# Generated by Django 6.0.5 on 2026-05-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='wp_app_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز عبور برنامه (Application Password)'),
        ),
        migrations.AddField(
            model_name='store',
            name='wp_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاربری ادمین وردپرس'),
        ),
    ]
